version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

exclude_patterns = [
  "**/migrations/**",
]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["requirements/production.txt"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"
  max_line_length = 120
  skip_doc_coverage = ["module", "magic", "init"]
  additional_builtins = ["_", "pretty_output"]
