version: 2.1

workflows:
  version: 2
  master:
    jobs:
      - backend_test

jobs:
  backend_test:
    working_directory: ~/repo

    environment:
      BASH_ENV: /home/circleci/.bashrc

    docker:
      - image: circleci/python:3.9.0
      - image: redis:4.0
      - image: postgres:12.3
        environment:
          POSTGRES_NAME: db
          POSTGRES_USER: db
          POSTGRES_DB: db
          POSTGRES_PASSWORD: password

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements/staging.txt" }}-{{ checksum "requirements/test.txt" }}

      - run:
          name: Install backend dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements/staging.txt
            pip install -r requirements/test.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/staging.txt" }}-{{ checksum "requirements/test.txt" }}

      - run:
          name: Run backend unit tests
          environment:
            POSTGRES_HOST: localhost
          command: |
            . venv/bin/activate
            DJANGO_SETTINGS_MODULE=config.settings.test coverage run manage.py test
            coverage xml
            CODECOV_TOKEN=$CODECOV_TOKEN bash <(curl -s https://codecov.io/bash) -f ./coverage.xml
