FROM python:3.13.6

LABEL maintainer="Beomjun Kang <kals323@gmail.com>"

ENV PYTHONUNBUFFERED 1

WORKDIR /webapps/django

COPY Pipfile* ./
COPY ./compose/backend/start-DEV.sh /start.sh

RUN apt-get update --no-install-recommends && \
    apt-get install -y -qq vim gettext && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --upgrade pip && \
    pip install pipenv && \
    pipenv install --system --dev --ignore-pipfile && \
    sed -i 's/\r//' /start.sh && \
    chmod +x /start.sh

COPY . .

ENTRYPOINT ["/start.sh"]
